#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=381206567429
BundleId=com.BlackRainbowApps.PinKeeper
ClientId=381206567429-de067tgmt8tpm27kn7ggmu2kk5g6092f.apps.googleusercontent.com

*/

#define kAppID "381206567429"
#define kBundleID "com.BlackRainbowApps.PinKeeper"
#define kClientID "381206567429-de067tgmt8tpm27kn7ggmu2kk5g6092f.apps.googleusercontent.com"

#endif


